/**
 * Generate the ambient module declarations and the name lists for the Astro
 * files that the integration exposes as virtual modules.
 *
 * Every file written here is overwritten wholesale, so none of them should be
 * edited by hand.
 */

import { writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { styleText } from "node:util";

import { getAllComponents, getAllLayouts } from "../utils/src_files";

const srcPath = resolve(import.meta.filename, "../../");
const header = "// File generated by `barrel` script.";

/**
 * Write a generated file inside `src/`, prefixed with the header that marks it
 * as generated.
 *
 * @param relPath the path of the file, relative to `src/`
 * @param body the contents of the file, without the header or trailing newline
 */
function writeGenerated(relPath: string, body: string) {
	writeFileSync(join(srcPath, relPath), `${header}\n\n${body}\n`, { encoding: "utf-8" });
	console.log(styleText("green", "BRL"), styleText("bold", `src/${relPath}`));
}

/**
 * Declare one module for the entire group, exporting every name from it.
 *
 * This is used for groups imported as `virtual:pf/<group>`.
 *
 * @param group the directory inside `src/` holding the group's `defs`
 * @param names the names of the Astro files in the group
 * @returns the declaration for the group's single virtual module
 */
function getBarrelDeclaration(group: string, names: string[]): string {
	const exports = names
		.map(
			(name) => `\texport const ${name}: typeof import("./${group}/defs/${name}.astro").default;`,
		)
		.join("\n");
	return `declare module "virtual:pf/${group}" {\n${exports}\n}`;
}

/**
 * Declare one module per name, each with a default export.
 *
 * This is used for groups imported as `virtual:pf/<group>/<Name>`, which lets a
 * page pull in only the files it actually uses instead of all of them.
 *
 * @param group the directory inside `src/` holding the group's `defs`
 * @param names the names of the Astro files in the group
 * @returns the declarations for the group's virtual modules
 */
function getModuleDeclarations(group: string, names: string[]): string {
	return names
		.map(
			(name) =>
				`declare module "virtual:pf/${group}/${name}" {
\tconst ${name}: typeof import("./${group}/defs/${name}.astro").default;
\texport default ${name};
}`,
		)
		.join("\n\n");
}

/**
 * The print width Oxfmt wraps at. Emitting the tuple below the way Oxfmt would
 * keeps regenerating a file from collapsing or expanding it, which would leave
 * the generated files perpetually dirty. `.oxfmtrc.json` does not override the
 * default, so this must be kept in sync if it ever does.
 */
const printWidth = 100;

/**
 * Build the `<kind>Names` tuple and the `<Kind>Name` union type derived from it.
 *
 * @param kind the singular, lowercase noun for one member of the group
 * @param names the names of the Astro files in the group
 * @returns the contents of the group's `index.ts`
 */
function getNameList(kind: string, names: string[]): string {
	const constName = `${kind}Names`;
	const typeName = `${kind.charAt(0).toUpperCase()}${kind.slice(1)}Name`;

	const oneLine = `export const ${constName} = [${names.map((name) => `"${name}"`).join(", ")}] as const;`;
	const tuple =
		oneLine.length <= printWidth
			? oneLine
			: `export const ${constName} = [\n${names.map((name) => `\t"${name}",`).join("\n")}\n] as const;`;

	return `${tuple}\nexport type ${typeName} = (typeof ${constName})[number];`;
}

// `getAllComponents` and `getAllLayouts` already return sorted names, so the
// generated files are stable without sorting again here.
const groups = [
	{
		dir: "components",
		kind: "component",
		names: await getAllComponents(),
		getDeclarations: getBarrelDeclaration,
	},
	{
		dir: "layouts",
		kind: "layout",
		names: await getAllLayouts(),
		getDeclarations: getModuleDeclarations,
	},
];

for (const { dir, kind, names, getDeclarations } of groups) {
	writeGenerated(`${dir}.d.ts`, getDeclarations(dir, names));
	writeGenerated(`${dir}/index.ts`, getNameList(kind, names));
}

console.log(
	styleText("green", "BRL"),
	styleText("green", groups.map(({ dir, names }) => `${names.length} ${dir}`).join(", ")),
);
console.log(styleText("green", "BRL"), "⚡️ Barrel success");
