/**
 * Collect all components from the code into a barrel types file.
 */

import { writeFileSync } from "node:fs";
import { resolve, join } from "node:path";
import { styleText } from "node:util";

import { globSync } from "glob";

const srcPath = resolve(import.meta.filename, "../../");

function getComponentMapping(allFiles: string[]): Record<string, string> {
	return Object.fromEntries(
		allFiles
			.map((astroFile): [string, string] => {
				const componentName =
					astroFile
						.split("/")
						.at(-1)
						?.replace(/\.astro$/u, "") ?? "";
				const importPath = `.${astroFile.split("/src")[1]}`;
				return [
					componentName,
					`export const ${componentName}: typeof import("${importPath}").default;`,
				];
			})
			.toSorted(([a], [b]) => a.localeCompare(b)),
	);
}

const allCompFiles = globSync(`${srcPath}/components/defs/*.astro`);
const allCompExports = getComponentMapping(allCompFiles);
const componentDTs = join(srcPath, "components.d.ts");
const componentDTsContent = `// File generated by \`barrel\` script.

declare module "virtual:pf/components" {
${Object.values(allCompExports)
	.map((line) => `\t${line}`)
	.join("\n")}
}
`;
writeFileSync(componentDTs, componentDTsContent, { encoding: "utf-8" });

const componentsIndex = join(srcPath, "components/index.ts");
const componentsIndexContent = `// File generated by \`barrel\` script.

export const componentNames = [
${Object.keys(allCompExports)
	.map((name) => `\t"${name}",`)
	.join("\n")}
] as const;
export type ComponentName = (typeof componentNames)[number];
`;
writeFileSync(componentsIndex, componentsIndexContent, { encoding: "utf-8" });

console.log(
	styleText("green", "BRL"),
	styleText("bold", "src/index.ts"),
	styleText("green", `${Object.keys(allCompExports).length} components`),
);
console.log(styleText("green", "BRL"), "⚡️ Barrel success");
