/**
 * Collect all components from the code into a barrel types file.
 */

import { writeFileSync } from "node:fs";
import { resolve, join } from "node:path";
import { styleText } from "node:util";

import { getAllComponents, getAllLayouts } from "../utils/src_files";

const srcPath = resolve(import.meta.filename, "../../");

function getComponentMapping(allFiles: string[]): Record<string, string> {
	return Object.fromEntries(
		allFiles
			.map((astroFile): [string, string] => {
				const importPath = `./components/defs/${astroFile}.astro`;
				return [astroFile, `export const ${astroFile}: typeof import("${importPath}").default;`];
			})
			.toSorted(([a], [b]) => a.localeCompare(b)),
	);
}

const allCompFiles = await getAllComponents();
const allCompExports = getComponentMapping(allCompFiles);
const componentDTs = join(srcPath, "components.d.ts");
const componentDTsContent = `// File generated by \`barrel\` script.

declare module "virtual:pf/components" {
${Object.values(allCompExports)
	.map((line) => `\t${line}`)
	.join("\n")}
}
`;
writeFileSync(componentDTs, componentDTsContent, { encoding: "utf-8" });

const componentsIndex = join(srcPath, "components/index.ts");
const componentsIndexContent = `// File generated by \`barrel\` script.

export const componentNames = [
${Object.keys(allCompExports)
	.map((name) => `\t"${name}",`)
	.join("\n")}
] as const;
export type ComponentName = (typeof componentNames)[number];
`;
writeFileSync(componentsIndex, componentsIndexContent, { encoding: "utf-8" });

const allLayoutFiles = await getAllLayouts();

const layoutsIndex = join(srcPath, "layouts/index.ts");
const layoutsIndexContent = `// File generated by \`barrel\` script.

export const layoutNames = [${allLayoutFiles.map((name) => `"${name}"`).join(", ")}] as const;
export type LayoutName = (typeof layoutNames)[number];
`;
writeFileSync(layoutsIndex, layoutsIndexContent, { encoding: "utf-8" });

console.log(
	styleText("green", "BRL"),
	styleText("bold", "src/index.ts"),
	styleText("green", `${Object.keys(allCompExports).length} components`),
);
console.log(styleText("green", "BRL"), "⚡️ Barrel success");
