// File generated by `barrel` script.

declare module "virtual:pf/components" {
	export const Anchor: typeof import("./components/defs/Anchor.astro").default;
	export const Brand: typeof import("./components/defs/Brand.astro").default;
	export const Breadcrumbs: typeof import("./components/defs/Breadcrumbs.astro").default;
	export const CertDetails: typeof import("./components/defs/CertDetails.astro").default;
	export const CertsTable: typeof import("./components/defs/CertsTable.astro").default;
	export const Comms: typeof import("./components/defs/Comms.astro").default;
	export const Elements: typeof import("./components/defs/Elements.astro").default;
	export const Entity: typeof import("./components/defs/Entity.astro").default;
	export const EpicCard: typeof import("./components/defs/EpicCard.astro").default;
	export const EpicDetails: typeof import("./components/defs/EpicDetails.astro").default;
	export const Footer: typeof import("./components/defs/Footer.astro").default;
	export const Header: typeof import("./components/defs/Header.astro").default;
	export const Icon: typeof import("./components/defs/Icon.astro").default;
	export const InstituteCard: typeof import("./components/defs/InstituteCard.astro").default;
	export const InstituteDetails: typeof import("./components/defs/InstituteDetails.astro").default;
	export const Language: typeof import("./components/defs/Language.astro").default;
	export const LanguageList: typeof import("./components/defs/LanguageList.astro").default;
	export const Letterhead: typeof import("./components/defs/Letterhead.astro").default;
	export const Nav: typeof import("./components/defs/Nav.astro").default;
	export const NowUpdate: typeof import("./components/defs/NowUpdate.astro").default;
	export const NowUpdates: typeof import("./components/defs/NowUpdates.astro").default;
	export const OrgCard: typeof import("./components/defs/OrgCard.astro").default;
	export const OrgDetails: typeof import("./components/defs/OrgDetails.astro").default;
	export const Period: typeof import("./components/defs/Period.astro").default;
	export const PfDate: typeof import("./components/defs/PfDate.astro").default;
	export const Post: typeof import("./components/defs/Post.astro").default;
	export const PostsTable: typeof import("./components/defs/PostsTable.astro").default;
	export const ProjectDetails: typeof import("./components/defs/ProjectDetails.astro").default;
	export const ProjectsTable: typeof import("./components/defs/ProjectsTable.astro").default;
	export const RoleDetails: typeof import("./components/defs/RoleDetails.astro").default;
	export const RolesTable: typeof import("./components/defs/RolesTable.astro").default;
	export const Skill: typeof import("./components/defs/Skill.astro").default;
	export const SkillList: typeof import("./components/defs/SkillList.astro").default;
	export const Table: typeof import("./components/defs/Table.astro").default;
	export const TechStack: typeof import("./components/defs/TechStack.astro").default;
	export const Toc: typeof import("./components/defs/Toc.astro").default;
}
