// File generated by `barrel` script.

declare module "virtual:pf/layouts/Entity" {
	const Entity: typeof import("./layouts/defs/Entity.astro").default;
	export default Entity;
}

declare module "virtual:pf/layouts/Og" {
	const Og: typeof import("./layouts/defs/Og.astro").default;
	export default Og;
}

declare module "virtual:pf/layouts/Post" {
	const Post: typeof import("./layouts/defs/Post.astro").default;
	export default Post;
}

declare module "virtual:pf/layouts/Print" {
	const Print: typeof import("./layouts/defs/Print.astro").default;
	export default Print;
}

declare module "virtual:pf/layouts/Root" {
	const Root: typeof import("./layouts/defs/Root.astro").default;
	export default Root;
}

declare module "virtual:pf/layouts/Web" {
	const Web: typeof import("./layouts/defs/Web.astro").default;
	export default Web;
}
